### ISSUE TITLE
Ability to cache on disk

### ISSUE THREAD

**Issue by NachoSoto** [NachoSoto/AsyncImageView#3]
### Tasks:
- [x] Create `RendererType` that reads and writes from a `CacheType`.
- [x] Create an implementation of`CacheType` for disk caching.
- [x] Rename `TypedCache<K, V>` to `InMemoryCache<K, V>`.
